---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: Inizia a utilizzare Astra Control Center verificando il supporto per cluster, applicazioni e browser Web Kubernetes. 
---
= Requisiti di Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Inizia verificando il supporto per cluster, applicazioni, licenze e browser web Kubernetes.



== Requisiti generali del cluster Kubernetes

Un cluster Kubernetes deve soddisfare i seguenti requisiti generali in modo da poterlo individuare e gestire da Astra Control Center.

* *Registro immagini*: È necessario disporre di un registro di immagini Docker privato in cui è possibile trasferire le immagini di build di Astra Control Center. È necessario disporre dell'URL del registro delle immagini in cui caricare le immagini e contrassegnare le immagini per il registro dei container privati.
* *Configurazione dello storage Trident / ONTAP*: Il centro di controllo Astra richiede che Trident versione 21.01 o 21.04 sia già installato e configurato per funzionare con NetApp ONTAP versione 9.5 o successiva come backend dello storage. Astra Control Center richiede la creazione e l'impostazione di una classe di storage come classe di storage predefinita. Centro di controllo Astra supporta i seguenti driver ONTAP forniti da Trident:
+
** ontap-nas
** ontap-nas-flexgroup
** ontap-san
** ontap-san-economy




Se si intende gestire il cluster Kubernetes da Astra Control Center e utilizzare il cluster per ospitare l'installazione di Astra Control Center, il cluster presenta i seguenti requisiti aggiuntivi:

* La versione più recente di Kubernetes https://kubernetes-csi.github.io/docs/snapshot-controller.html["componente snapshot-controller"^] è installato
* Un Trident https://netapp-trident.readthedocs.io/en/latest/kubernetes/concepts/objects.html?highlight=VolumeSnapshotClass#kubernetes-volumesnapshotclass-objects["oggetto volumesnapshotclass"^] è stato definito da un amministratore
* Nel cluster esiste una classe di storage Kubernetes predefinita
* Almeno una classe di storage è configurata per utilizzare Trident
* Metodo per indirizzare l'FQDN di Astra Control Center all'indirizzo IP esterno del servizio Astra Control Center




=== Cluster OpenShift

Centro di controllo Astra richiede un cluster Red Hat OpenShift Container Platform 4.6.8 o 4.7 con classi di storage Trident supportate da ONTAP 9.5 o versione successiva, con i seguenti attributi:

* Almeno 300 GB di capacità di storage ONTAP disponibile
* 3 nodi controller con 4 core CPU, 16 GB di RAM e 120 GB di storage disponibili ciascuno
* 3 nodi di lavoro con almeno 12 core CPU, 32 GB di RAM e 50 GB di storage disponibili ciascuno
* Kubernetes versione 1.19 o 1.20
* Tipo di servizio "LoadBalancer" disponibile per il traffico in ingresso da inviare ai servizi nel cluster OpenShift
* Metodo per indirizzare l'FQDN di Astra Control Center all'indirizzo IP con bilanciamento del carico



NOTE: Questi requisiti minimi presuppongono che Astra Control Center sia l'unica applicazione in esecuzione sul cluster OpenShift. Se il cluster esegue applicazioni aggiuntive, è necessario modificare di conseguenza questi requisiti minimi.

Assicurarsi che il cluster soddisfi i requisiti minimi e seguire le Best practice di Kubernetes in modo che Astra Control Center sia altamente disponibile nel cluster Kubernetes.


NOTE: OpenShift 4.8 non è supportato.

[NOTE]
====
Durante la clonazione dell'applicazione, Astra Control Center deve consentire a OpenShift di montare volumi e modificare la proprietà dei file. Per questo motivo, ONTAP deve essere configurato in modo da consentire il completamento corretto delle operazioni del volume utilizzando i seguenti comandi:

. `export-policy rule modify -vserver svm0 -policyname default -ruleindex 1 -superuser sys`
. `export-policy rule modify -policyname default -ruleindex 1 -anon 65534`


====

NOTE: Se si intende aggiungere un secondo cluster OpenShift 4.6 o 4.7 come risorsa di calcolo gestita, è necessario assicurarsi che la funzione Trident Volume Snapshot sia attivata. Vedi il Trident ufficiale https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/operations/tasks/volumes/snapshots.html?highlight=volumesnapshot#on-demand-volume-snapshots["istruzioni"^] Per attivare e testare le istantanee dei volumi con Trident.



=== Requisiti di gestione delle applicazioni

Astra Control Center ha i seguenti requisiti di gestione delle applicazioni:

* *Licensing*: È necessaria una licenza Astra Control Center per gestire le applicazioni utilizzando Astra Control Center.
* *Helm 3*: Se utilizzi Helm per implementare le app, Astra Control Center richiede Helm versione 3. La gestione e la clonazione delle applicazioni implementate con Helm 3 (o aggiornate da Helm 2 a Helm 3) sono completamente supportate. Le app implementate con Helm 2 non sono supportate.
* *Gestione degli operatori*: Astra Control Center non supporta le applicazioni implementate con operatori abilitati per Operator Lifecycle Manager (OLM) o con gli operatori con ambito cluster.




== Accesso a Internet

È necessario determinare se si dispone di un accesso esterno a Internet. In caso contrario, alcune funzionalità potrebbero essere limitate, ad esempio la ricezione di dati di monitoraggio e metriche da NetApp Cloud Insights o l'invio di pacchetti di supporto al sito di supporto NetApp.



== Licenza

Astra Control Center richiede una licenza Astra Control Center per una funzionalità completa. Ottenere una licenza di valutazione o una licenza completa da NetApp. Senza una licenza, non sarà possibile:

* Definire applicazioni personalizzate
* Creare snapshot o cloni di applicazioni esistenti
* Configurare le policy di protezione dei dati


Se si desidera provare Astra Control Center, è possibile link:setup_overview.html#add-a-full-or-evaluation-license["utilizzare una licenza di valutazione di 90 giorni"].



== Tipo di servizio "LoadBalancer" per cluster Kubernetes on-premise

Astra Control Center utilizza un servizio del tipo "LoadBalancer" (svc/traefik nello spazio dei nomi di Astra Control Center) e richiede l'assegnazione di un indirizzo IP esterno accessibile. Per i cluster OpenShift on-premise, è possibile utilizzare https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_LB_MetalLB.html#installing-the-metallb-load-balancer["MetalLB"^] Per assegnare automaticamente un indirizzo IP esterno al servizio. Nella configurazione del server DNS interno, puntare il nome DNS scelto per Astra Control Center sull'indirizzo IP con bilanciamento del carico.



== Requisiti di rete

Il cluster che ospita Astra Control Center comunica utilizzando le seguenti porte TCP. Assicurarsi che queste porte siano consentite attraverso qualsiasi firewall e configurare i firewall in modo da consentire qualsiasi traffico HTTPS in uscita dalla rete Astra. Alcune porte richiedono la connettività tra il cluster che ospita Astra Control Center e ciascun cluster gestito (annotato dove applicabile).

|===
| Prodotto | Porta | Protocollo | Direzione | Scopo 


| Centro di controllo Astra | 443 | HTTPS | Ingresso | Accesso UI/API - assicurarsi che questa porta sia aperta in entrambi i modi tra il cluster che ospita Astra Control Center e ciascun cluster gestito 


| Centro di controllo Astra | 9090 | HTTPS  a| 
* Ingresso (al cluster che ospita Astra Control Center)
* Egress (porta casuale dall'indirizzo IP del nodo di ciascun nodo di lavoro di ciascun cluster gestito)

| Dati delle metriche per il cliente: Assicurarsi che ogni cluster gestito possa accedere a questa porta sul cluster che ospita Astra Control Center 


| Trident | 34571 | HTTPS | Ingresso | Comunicazione del nodo pod 


| Trident | 9220 | HTTP | Ingresso | Endpoint delle metriche 
|===


== Browser Web supportati

Astra Control Center supporta versioni recenti di Firefox, Safari e Chrome con una risoluzione minima di 1280 x 720.



== Cosa succederà

Visualizzare il link:quick-start.html["avvio rapido"] panoramica.
